[package]
name = "c2enc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
libcodec2 = { version = "0.1.0", path = "../libcodec2" }
